---
# tasks file to install packages

#add mariadb repo
- name: Adding MariaDB Repo
  template:
    src: mariadb.repo.j2
    dest: /etc/yum.repos.d/mariadb.repo
    mode: 0644
    owner: root
    group: root
  when: mariadb_repo

# clean yum metadata cache
- name: clean yum metadata cache
  command: yum clean metadata
  args:
    warn: no

# install mariadb packages
- name: "[CentOS] Ensure MariaDB packages are installed."
  yum:
    name: "{{ mariadb_packages }}"
    state: installed

# maridb daemon user
- name: Create Mariadb user
  user:
    name: "{{ mariadb_daemon_user }}"
    group: "{{ mariadb_daemon_user }}"
    system: yes 
    comment: "Created by Ansible"

# Delete default Directories created during installation
- name: remove unwanted default mariadb directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ mariadb_config_dir }}"
    - "{{ mariadb_default_data_dir }}"

# Mariadb diretories needed
- name: Create required directories for MariaDB
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mariadb_daemon_user }}"
    group: "{{ mariadb_daemon_user }}"
    mode: 0755
    recurse: yes
  with_items:
    - "{{ mariadb_data_dir }}"
    - "{{ mariadb_pid_dir }}"
    - "{{ mariadb_log_dir }}"
    - "{{ mariadb_config_dir }}"
    - "{{ mariadb_backup_dir }}"

# Add configuration files
- name: Adding Galera Configuration.
  template:
    src: cluster.cnf.j2
    dest: "{{ mariadb_config_dir }}/server.cnf"
    owner: root
    group: root
    mode: 0644

- name: Adding Galera Configuration.
  template:
    src: my.cnf.j2
    dest: "/etc/my.cnf"
    owner: root
    group: root
    mode: 0644

# initialise mariadb data directory
- name: initialise mariadb data directory
  shell:  mysql_install_db --user=mysql --datadir={{ mariadb_data_dir }} --datadir={{ mariadb_data_dir }} 

# Changing SELinux's Mode
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

#  Enable firewalld
- name: Start and enable firewalld
  service: 
    name: firewalld
    state: started
    enabled: yes

- name: enable mariadb port access
  firewalld:
    service: mysql
    permanent: yes
    state: enabled
    immediate: true 

- name: Open Galera ports on firewall
  firewalld:
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - 4444/tcp
    - 4567/tcp
    - 4568/tcp

# remove un wanted settings
- name: Remove migrated-from-my.cnf-settings.conf 
  file:
    path: /etc/systemd/system/mariadb.service.d/migrated-from-my.cnf-settings.conf
    state: absent

- name: reload systemd for MariaDB changes
  become: true
  systemd:
    daemon_reload: true

# initialise galera cluster
- name: initialise galera cluster
  shell: galera_new_cluster

# Configure mariadb
- name: Ensure MariaDB is started and enabled on boot.
  service:
    name: "{{ mariadb_daemon }}"
    enabled: yes
    state: started